# Generated by Django 5.1.3 on 2024-12-02 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='aprobado',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha_solicitud',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tipo_prestamo',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('HIPOTECARIO', 'Hipotecario'), ('AUTOMOTOR', 'Automotor')], default='Personal', max_length=20),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='cuentas.cuenta'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
