# Generated by Django 5.1.3 on 2024-11-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(default='Cliente', max_length=10),
        ),
    ]
