# Generated by Django 5.1.3 on 2024-11-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_tipo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Admin', 'Admin'), ('Empleado', 'Empleado')], default='Cliente', max_length=10),
        ),
    ]
