# Generated by Django 5.1.3 on 2024-12-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0005_alter_tarjeta_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='cvv',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
